name: Deploy Lambda to AWS

on:
  workflow_call:
    inputs:
      file_path:
        required: true
        type: string
      lambda_name:
        required: true
        type: string

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: x64

      - name: Install Python module
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r ${{ inputs.file_path }}/requirements.txt
      - name: Python files to Zip file
        run: |
          (cd ./venv/lib/python3.9/site-packages; zip -r9 ../../../../Build_${{ inputs.lambda_name }}.zip .)
          (zip Build_${{ inputs.lambda_name }}.zip -j ./backend/common/*;)
          (zip Build_${{ inputs.lambda_name }}.zip -j ${{ inputs.file_path }}/*;)
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v3
        with:
          name: veloghelper
          path: Build_${{ inputs.lambda_name }}.zip
          if-no-files-found: error

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Download Lambda Build.zip
        uses: actions/download-artifact@v3
        with:
          name: veloghelper

      - name: Upload to S3
        run: aws s3 cp Build_${{ inputs.lambda_name }}.zip s3://serverless-veloghelper-s3/Build_${{ inputs.lambda_name }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy ${{ inputs.lambda_name }}
        run: aws lambda update-function-code --function-name ${{ inputs.lambda_name }} --s3-bucket serverless-veloghelper-s3 --s3-key Build_${{ inputs.lambda_name }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
