name: Call Deploy Action

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  Deploy:
    strategy:
      matrix:
        lambda:
          [
            VH__get-blog,
            VH__get-user,
            VH__create-user,
            VH__get-bookmarked-blogs,
            VH__add-bookmark-blog,
            VH__delete-bookmark-blog,
          ]
        include:
          - lambda: VH__get-blog
            path: ./backend/api/get_blog
          - lambda: VH__get-user
            path: ./backend/api/get_user
          - lambda: VH__create-user
            path: ./backend/api/create_user
          - lambda: VH__get-bookmarked-blogs
            path: ./backend/api/get_bookmarked_blogs
          - lambda: VH__add-bookmark-blog
            path: ./backend/api/add_bookmark_blog
          - lambda: VH__delete-bookmark-blog
            path: ./backend/api/delete_bookmark_blog

    uses: junah201/velog-helper/.github/workflows/deploy.yml@main
    with:
      file_path: ${{ matrix.path }}
      lambda_name: ${{ matrix.lambda }}
    secrets: inherit
